import Provider from "@/components/provider";
import Sidebar from "@/components/sidbar";
import ProviderQuery from "@/query/query-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <ProviderQuery>
            <Toaster />

            <div className="w w-full block  h-full sm:flex">
              <div className="w-[180px] md:w-[200px]  lg:w-[20%] mr-4 bg-white  p-4  ">
                <Sidebar />
                {/* <Header />
        <Kk /> */}
              </div>
              <div className="w-[80%]  p-4">{children}</div>
            </div>
          </ProviderQuery>
        </Provider>
      </body>
    </html>
  );
}
